Repository react-dates/react-dates, pull requests merged in 2018-05, with the labels that each got.

#1157 Force input border radius to be 0
  src/components/DateInput.jsx
  src/theme/DefaultTheme.js
Labels: semver-patch: fixes/refactors/etc

#994 The min-nights modifiers should get cleared according to the previous prop value not the new one
  src/components/DayPickerRangeController.jsx
  test/components/DayPickerRangeController_spec.jsx
Labels: semver-patch: fixes/refactors/etc

#1158 Tweak default react-dates styling
  src/components/DateInput.jsx
  src/components/DateRangePickerInput.jsx
  src/theme/DefaultTheme.js
Labels: semver-patch: fixes/refactors/etc

#1160 make nav buttons optional
  examples/DayPickerRangeControllerWrapper.jsx
  src/components/DayPicker.jsx
  src/components/DayPickerRangeController.jsx
  stories/DayPickerRangeController.js
  test/components/DayPickerRangeController_spec.jsx
Labels: semver-minor: new stuff

#1168 Replace dumb quotes with smart quotes
  src/defaultPhrases.js
Labels: semver-patch: fixes/refactors/etc

#1190 Add focusable="false" to dls-web svgs
  src/svg/arrow-left.svg
  src/svg/arrow-right.svg
  src/svg/calendar.svg
  src/svg/chevron-down.svg
  src/svg/chevron-up.svg
  src/svg/close.svg
Labels: accessibility, semver-patch: fixes/refactors/etc
