Repository react-dates/react-dates, pull requests merged in 2018-09, with the labels that each got.

#1322 Remove propTypes in production
  .babelrc
  .eslintrc
  package.json
Labels: semver-major: breaking change

#1345 Only blur the activeElement after the month transition if available.
  src/components/DayPicker.jsx
Labels: semver-patch: fixes/refactors/etc

#1347 Center vertical month navigation
  src/components/DayPickerNavigation.jsx
Labels: semver-patch: fixes/refactors/etc

#1350 Remove svgo from "inline-react-svg" babel plugin options
  .babelrc
Labels: semver-patch: fixes/refactors/etc

#1344 Readme css var update
  README.md
Labels: documentation

#1355 Address missing daypicker width when calendarMonthPadding theme variable is undefined
  src/utils/getCalendarMonthWidth.js
  test/utils/getCalendarMonthWidth_spec.js
Labels: semver-patch: fixes/refactors/etc

#1360 Add SingleDatePickerInputController component
  src/components/SingleDatePicker.jsx
  src/components/SingleDatePickerInput.jsx
  src/components/SingleDatePickerInputController.jsx
  test/components/SingleDatePickerInputController_spec.jsx
  test/components/SingleDatePicker_spec.jsx
Labels: semver-minor: new stuff

#1364 Add `horizontalMonthPadding` to the DRP
  src/components/DateRangePicker.jsx
  src/shapes/DateRangePickerShape.js
Labels: semver-minor: new stuff

#1363 Address DayPickerNavigation rerender
  src/components/DayPicker.jsx
  test/components/DayPicker_spec.jsx
Labels: performance, semver-patch: fixes/refactors/etc

#1370 Pass `isOutsideRange` prop to input controller
  src/components/SingleDatePicker.jsx
  test/components/SingleDatePicker_spec.jsx
Labels: semver-minor: new stuff
