Repository react-dates/react-dates, pull requests merged in 2018-04, with the labels that each got.

#984 Add dayAriaLabelFormat into DatePickerRange and SingleDatePicker
  README.md
  src/components/DateRangePicker.jsx
  src/components/SingleDatePicker.jsx
  src/shapes/DateRangePickerShape.js
  src/shapes/SingleDatePickerShape.js
Labels: semver-minor: new stuff

#1038 Add about "inputIconPosition" prop to readme and storybook
  README.md
  stories/DateRangePicker_input.js
  stories/SingleDatePicker_input.js
Labels: documentation

#1107 Fixed unexpected blur call
  src/components/DayPicker.jsx
Labels: semver-patch: fixes/refactors/etc

#1096 add verticalSpacing prop
  examples/DayPickerRangeControllerWrapper.jsx
  src/components/CalendarMonth.jsx
  src/components/CalendarMonthGrid.jsx
  src/components/DayPicker.jsx
  src/components/DayPickerRangeController.jsx
  stories/DayPickerRangeController.js
Labels: feature request

#1115 Patch onOutsideClick default value in the DayPickerSingleDateController
  src/components/DayPickerSingleDateController.jsx
Labels: semver-patch: fixes/refactors/etc
