Repository react-dates/react-dates, pull requests merged in 2018-06, with the labels that each got.

#1191 Deprecate internal OutsideClickHandler in favor of react-outside-click-handler package
  .nycrc
  package.json
  src/components/DateRangePicker.jsx
  src/components/DayPicker.jsx
  src/components/OutsideClickHandler.jsx
  src/components/SingleDatePicker.jsx
  test/components/OutsideClickHandler_spec.jsx
Labels: semver-patch: fixes/refactors/etc

#1192 Change month height calculation to be based on number of weeks instead of DOM calculations
  src/components/CalendarMonth.jsx
  src/components/CalendarMonthGrid.jsx
  src/components/DayPicker.jsx
  src/utils/getNumberOfCalendarMonthWeeks.js
  test/components/CalendarMonthGrid_spec.jsx
  test/utils/getNumberOfCalendarMonthWeeks_spec.js
Labels: semver-major: breaking change

#1207 Pass nextMonth to prev and next month click props
  src/components/DayPicker.jsx
Labels: semver-minor: new stuff

#1218 Allow consolidated-events ^2.0.0
  package.json
Labels: semver-minor: new stuff

#1214 Remove inputRef.blur() call that was causing a focus trap in Safari/IE
  src/components/DateInput.jsx
  test/components/DateInput_spec.jsx
Labels: semver-patch: fixes/refactors/etc

#1106 [Issue 25] Unopinionated month and year selection support
  README.md
  src/components/CalendarMonth.jsx
  src/components/CalendarMonthGrid.jsx
  src/components/DateRangePicker.jsx
  src/components/DayPicker.jsx
  src/components/DayPickerRangeController.jsx
  src/components/DayPickerSingleDateController.jsx
  src/components/SingleDatePicker.jsx
  src/shapes/DateRangePickerShape.js
  src/shapes/SingleDatePickerShape.js
  src/utils/isNextMonth.js
  src/utils/isPrevMonth.js
  src/utils/isSameMonth.js
  stories/DayPickerRangeController.js
  stories/DayPickerSingleDateController.js
  test/components/CalendarMonthGrid_spec.jsx
  test/components/DayPicker_spec.jsx
  test/utils/isNextMonth_spec.js
  test/utils/isPrevMonth_spec.js
  test/utils/isSameMonth_spec.js
Labels: semver-minor: new stuff

#1220 Rename renderMonth to renderMonthTitle and renderCaption to renderMonthElement
  README.md
  examples/DateRangePickerWrapper.jsx
  examples/PresetDateRangePicker.jsx
  examples/SingleDatePickerWrapper.jsx
  src/components/CalendarMonth.jsx
  src/components/CalendarMonthGrid.jsx
  src/components/DateRangePicker.jsx
  src/components/DayPicker.jsx
  src/components/DayPickerRangeController.jsx
  src/components/DayPickerSingleDateController.jsx
  src/components/SingleDatePicker.jsx
  src/shapes/DateRangePickerShape.js
  src/shapes/SingleDatePickerShape.js
  stories/DateRangePicker.js
  stories/DayPickerRangeController.js
  stories/DayPickerSingleDateController.js
  stories/SingleDatePicker.js
Labels: semver-major: breaking change

#1204 Remove default styling (border, etc.) from custom month nav buttons
  src/components/DayPickerNavigation.jsx
  stories/DateRangePicker_calendar.js
  stories/DayPickerRangeController.js
Labels: semver-major: breaking change

#1225 Remove OutsideClickHandler export
  src/components/OutsideClickHandler.jsx
  src/index.js
Labels: semver-major: breaking change
