Repository react-dates/react-dates, pull requests merged in 2019-09, with the labels that each got.

#1775 [new][deps] Update dependencies related to react-with-styles
  package.json
Labels: semver-minor: new stuff

#1761 [breaking] [deps] Update react-with-styles and other deps
  .eslintrc
  .storybook/config.js
  package.json
  scripts/buildCSS.js
  scripts/renderAllComponents.jsx
Labels: semver-major: breaking change

#1781 [fix][deps] Update react-with-styles from 4.0.0 -> 4.0.1
  .travis.yml
  package.json
Labels: semver-patch: fixes/refactors/etc

#1577 Pull Request for bug ticket #1575.
  src/components/DayPicker.jsx
  test/components/DayPicker_spec.jsx
Labels: semver-patch: fixes/refactors/etc

#1783 Combine labelled DayPicker container elements
  src/components/DayPicker.jsx
Labels: accessibility

#1787 Add a render function for customizable week header text
  src/components/DateRangePicker.jsx
  src/components/DayPicker.jsx
  src/components/DayPickerRangeController.jsx
  src/components/DayPickerSingleDateController.jsx
  src/components/SingleDatePicker.jsx
  src/shapes/DateRangePickerShape.js
  src/shapes/SingleDatePickerShape.js
  stories/DayPicker.js
  test/components/DayPicker_spec.jsx
Labels: semver-minor: new stuff

#1784 Add support for positioning month navigation under the calendar
  examples/DateRangePickerWrapper.jsx
  src/components/DateRangePicker.jsx
  src/components/DayPicker.jsx
  src/components/DayPickerNavigation.jsx
  src/components/DayPickerRangeController.jsx
  src/components/DayPickerSingleDateController.jsx
  src/components/SingleDatePicker.jsx
  src/constants.js
  src/shapes/DateRangePickerShape.js
  src/shapes/NavPositionShape.js
  src/shapes/SingleDatePickerShape.js
  stories/DateRangePicker_calendar.js
  stories/DayPickerRangeController.js
  stories/DayPickerSingleDateController.js
  test/components/DayPickerNavigation_spec.jsx
  test/components/DayPicker_spec.jsx
Labels: semver-minor: new stuff
