Repository react-dates/react-dates, pull requests merged in 2019-05, with the labels that each got.

#1652 Docs : added initialVisibleMonth to DayPickerRangeController in ReadMe
  README.md
Labels: documentation

#1655 Compile classes in loose mode
  .babelrc
Labels: performance, semver-patch: fixes/refactors/etc

#1656 Optimize toISODateString and toISOMonthString
  src/constants.js
  src/utils/toISODateString.js
  src/utils/toISOMonthString.js
  test/utils/toISODateString_spec.js
Labels: performance, semver-patch: fixes/refactors/etc

#1657 Optimize isDayVisible
  src/utils/isDayVisible.js
  test/utils/isDayVisible_spec.js
Labels: performance, semver-patch: fixes/refactors/etc

#1661 Add caching to isDayVisible
  src/utils/isDayVisible.js
Labels: performance

#1662 Avoid some moment object creation in modifier generation
  src/components/DayPickerRangeController.jsx
  src/components/DayPickerSingleDateController.jsx
  src/utils/getPreviousMonthMemoLast.js
Labels: performance

#1659 Optimize deleteModifier/addModifier
  src/components/DayPickerRangeController.jsx
  src/components/DayPickerSingleDateController.jsx
  test/components/DayPickerRangeController_spec.jsx
  test/components/DayPickerSingleDateController_spec.jsx
Labels: performance, semver-patch: fixes/refactors/etc

#1663 Cache some moment instances when rebuilding modifiers
  src/components/DayPickerRangeController.jsx
  src/components/DayPickerSingleDateController.jsx
  src/utils/getPooledMoment.js
  test/utils/getPooledMoment_spec.js
Labels: performance, semver-patch: fixes/refactors/etc
