Repository react-dates/react-dates, pull requests merged in 2019-02, with the labels that each got.

#1252 Add date offset functionality to DateRangePicker
  src/components/DateRangePicker.jsx
  src/components/DayPickerRangeController.jsx
  src/shapes/DateRangePickerShape.js
  stories/DateRangePicker_calendar.js
  test/components/DateRangePicker_spec.jsx
  test/components/DayPickerRangeController_spec.jsx
Labels: semver-minor: new stuff

#1524 Fixes the focus out event in IE11
  src/components/DateRangePicker.jsx
  test/components/DateRangePicker_spec.jsx
Labels: semver-patch: fixes/refactors/etc

#1540 Fix date selection issue with withPortal or appendToBody. Fixes #1535.
  src/components/SingleDatePicker.jsx
  test/components/SingleDatePicker_spec.jsx
Labels: semver-patch: fixes/refactors/etc

#1555 Fix VO issue for date ranges
  src/components/CalendarDay.jsx
  src/utils/getCalendarDaySettings.js
  test/components/CalendarDay_spec.jsx
Labels: semver-patch: fixes/refactors/etc

#1563 Focus ring now shows up around custom navigation buttons
  .gitignore
  src/components/DayPickerNavigation.jsx
  stories/DayPicker.js
  test/components/DayPickerNavigation_spec.jsx
Labels: semver-major: breaking change

#1468 Added clearTimeout for the setCalendarMonthGridHeight timeout
  src/components/DayPicker.jsx
Labels: semver-patch: fixes/refactors/etc

#1538 Remove last-in-range style modifiers to fix border issue
  src/components/CalendarDay.jsx
  src/components/CustomizableCalendarDay.jsx
Labels: semver-patch: fixes/refactors/etc

#1547 add hovered-start-blocked-minimun-nights and hovered-start-first-possible-end modifiers
  src/components/CalendarDay.jsx
  src/components/CustomizableCalendarDay.jsx
  src/components/DayPickerRangeController.jsx
  stories/DayPickerRangeController.js
  test/components/DayPickerRangeController_spec.jsx
Labels: semver-minor: new stuff
