Repository react-dates/react-dates, pull requests merged in 2021-11, with the labels that each got.

#2084 [Fix] `DateRangePicker`, `DateRangePickerInput`: Fix keyboard navigation for second input
  src/components/DateRangePicker.jsx
  src/components/DateRangePickerInput.jsx
  test/components/DateRangePicker_spec.jsx
Labels: semver-patch: fixes/refactors/etc

#2155 [New] DateInput, {DateRange,SingleDate}Picker{,Input,InputController}: add autocomplete prop
  README.md
  examples/DateRangePickerWrapper.jsx
  examples/SingleDatePickerWrapper.jsx
  src/components/DateInput.jsx
  src/components/DateRangePicker.jsx
  src/components/DateRangePickerInput.jsx
  src/components/DateRangePickerInputController.jsx
  src/components/SingleDatePicker.jsx
  src/components/SingleDatePickerInput.jsx
  src/components/SingleDatePickerInputController.jsx
  src/shapes/DateRangePickerShape.js
  src/shapes/SingleDatePickerShape.js
  stories/DateRangePicker.js
  stories/SingleDatePicker.js
Labels: semver-minor: new stuff

#1992 [readme] Add `verticalSpacing`
  README.md
Labels: documentation

#1481 [Fix] `DayPicker`, `DayPickerSingleDateController`: Snap to new date if date is off screen
  src/components/DayPicker.jsx
  src/components/DayPickerSingleDateController.jsx
  test/components/DayPickerSingleDateController_spec.jsx
  test/components/DayPicker_spec.jsx
Labels: semver-patch: fixes/refactors/etc
